// 项目级 build.gradle
// 作用：声明所有子模块要用到的插件版本（这里只声明，不应用）
plugins {
    id 'com.android.application' version '8.1.4' apply false
    id 'org.jetbrains.kotlin.android' version '1.9.10' apply false
    // KSP 版本必须严格匹配 Kotlin 版本（Kotlin 1.9.10 → KSP 1.9.10-1.0.13）
    id 'com.google.devtools.ksp' version '1.9.10-1.0.13' apply false
}
