// settings.gradle - 工程入口配置
// 作用：定义项目名、模块、仓库地址
pluginManagement {
    repositories {
        // 只用官方仓库（google() 国内可访问）
        google()
        gradlePluginPortal()
        mavenCentral()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "WageManager"
include ':app'